set_property PACKAGE_PIN AA18 [get_ports adc_ck]
set_property IOSTANDARD LVCMOS12 [get_ports adc_ck]
set_property SLEW SLOW [get_ports adc_ck]
set_property PULLDOWN true [get_ports adc_ck]
set_property PACKAGE_PIN AB24 [get_ports adc_start]
set_property IOSTANDARD LVCMOS12 [get_ports adc_start]
set_property SLEW SLOW [get_ports adc_start]
set_property PULLDOWN true [get_ports adc_start]
set_property PACKAGE_PIN A9 [get_ports btn_reset]
set_property IOSTANDARD LVCMOS33 [get_ports btn_reset]
set_property PULLDOWN true [get_ports btn_reset]
set_property PACKAGE_PIN Y18 [get_ports csa_reset_n]
set_property IOSTANDARD LVCMOS12 [get_ports csa_reset_n]
set_property SLEW SLOW [get_ports csa_reset_n]
set_property PULLDOWN true [get_ports csa_reset_n]
set_property IOSTANDARD LVCMOS12 [get_ports dac_sck]
set_property SLEW SLOW [get_ports dac_sck]
set_property PACKAGE_PIN AB17 [get_ports dac_sck]
set_property PULLDOWN true [get_ports dac_sck]
set_property PACKAGE_PIN Y17 [get_ports dac_sdin]
set_property IOSTANDARD LVCMOS12 [get_ports dac_sdin]
set_property SLEW SLOW [get_ports dac_sdin]
set_property PULLDOWN true [get_ports dac_sdin]
set_property PACKAGE_PIN AA17 [get_ports dac_sync_n]
set_property IOSTANDARD LVCMOS12 [get_ports dac_sync_n]
set_property SLEW SLOW [get_ports dac_sync_n]
set_property PULLUP true [get_ports dac_sync_n]
set_property PACKAGE_PIN AC22 [get_ports inj_stb]
set_property IOSTANDARD LVCMOS12 [get_ports inj_stb]
set_property SLEW FAST [get_ports inj_stb]
set_property PULLDOWN true [get_ports inj_stb]
set_property PACKAGE_PIN W12 [get_ports rx_ser]
set_property IOSTANDARD LVCMOS33 [get_ports rx_ser]
set_property PULLUP true [get_ports rx_ser]
set_property PACKAGE_PIN AC17 [get_ports sel_ckcol]
set_property IOSTANDARD LVCMOS12 [get_ports sel_ckcol]
set_property SLEW SLOW [get_ports sel_ckcol]
set_property PULLDOWN true [get_ports sel_ckcol]
set_property PACKAGE_PIN AF23 [get_ports sel_ckrow]
set_property IOSTANDARD LVCMOS12 [get_ports sel_ckrow]
set_property SLEW SLOW [get_ports sel_ckrow]
set_property PULLDOWN true [get_ports sel_ckrow]
set_property PACKAGE_PIN AA20 [get_ports sel_init_n]
set_property IOSTANDARD LVCMOS12 [get_ports sel_init_n]
set_property SLEW SLOW [get_ports sel_init_n]
set_property PULLUP true [get_ports sel_init_n]
set_property PACKAGE_PIN AE16 [get_ports ser_ck]
set_property IOSTANDARD LVCMOS12 [get_ports ser_ck]
set_property SLEW SLOW [get_ports ser_ck]
set_property PULLDOWN true [get_ports ser_ck]
set_property PACKAGE_PIN AE17 [get_ports ser_out]
set_property IOSTANDARD LVCMOS12 [get_ports ser_out]
set_property PACKAGE_PIN AD16 [get_ports ser_read]
set_property IOSTANDARD LVCMOS12 [get_ports ser_read]
set_property SLEW SLOW [get_ports ser_read]
set_property PULLDOWN true [get_ports ser_read]
set_property PACKAGE_PIN AF17 [get_ports ser_reset_n]
set_property IOSTANDARD LVCMOS12 [get_ports ser_reset_n]
set_property SLEW SLOW [get_ports ser_reset_n]
set_property PULLDOWN true [get_ports ser_reset_n]
set_property IOSTANDARD LVCMOS12 [get_ports sh_phi1d_inf]
set_property SLEW SLOW [get_ports sh_phi1d_inf]
set_property PULLDOWN true [get_ports sh_phi1d_inf]
set_property PACKAGE_PIN AC26 [get_ports sh_phi1d_inf]
set_property PACKAGE_PIN AC24 [get_ports sh_phi1d_sup]
set_property IOSTANDARD LVCMOS12 [get_ports sh_phi1d_sup]
set_property SLEW SLOW [get_ports sh_phi1d_sup]
set_property PULLDOWN true [get_ports sh_phi1d_sup]
set_property PACKAGE_PIN AB26 [get_ports slow_ctrl_ck]
set_property IOSTANDARD LVCMOS12 [get_ports slow_ctrl_ck]
set_property SLEW SLOW [get_ports slow_ctrl_ck]
set_property PULLDOWN true [get_ports slow_ctrl_ck]
set_property PACKAGE_PIN AD26 [get_ports slow_ctrl_in]
set_property IOSTANDARD LVCMOS12 [get_ports slow_ctrl_in]
set_property SLEW SLOW [get_ports slow_ctrl_in]
set_property PULLDOWN true [get_ports slow_ctrl_in]
set_property PACKAGE_PIN AB25 [get_ports slow_ctrl_reset_n]
set_property IOSTANDARD LVCMOS12 [get_ports slow_ctrl_reset_n]
set_property SLEW SLOW [get_ports slow_ctrl_reset_n]
set_property PULLDOWN true [get_ports slow_ctrl_reset_n]
set_property PACKAGE_PIN W13 [get_ports tx_ser]
set_property IOSTANDARD LVCMOS33 [get_ports tx_ser]
set_property SLEW SLOW [get_ports tx_ser]
set_property PULLUP true [get_ports tx_ser]
set_property IOSTANDARD LVCMOS12 [get_ports daq_ck]
set_property PACKAGE_PIN AC19 [get_ports daq_ck]
set_property PULLDOWN true [get_ports daq_ck]
create_clock -period 10.000 -name daq_ck -waveform {0.000 5.000} [get_ports daq_ck]
create_generated_clock -name uart_ck_reg_n_0 -source [get_ports daq_ck] -divide_by 10 [get_pins uart_ck_reg/Q]
create_clock -period 100.000 -name VIRTUAL_uart_ck_reg_n_0 -waveform {0.000 50.000}
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports adc_ck]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports adc_ck]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports adc_start]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports adc_start]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports csa_reset_n]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports csa_reset_n]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports dac_sck]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports dac_sck]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports dac_sync_n]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports dac_sync_n]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports sel_ckcol]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports sel_ckcol]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports sel_ckrow]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports sel_ckrow]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports sel_init_n]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports sel_init_n]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports ser_ck]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports ser_ck]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports ser_read]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports ser_read]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports ser_reset_n]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports ser_reset_n]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports sh_phi1d_inf]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports sh_phi1d_inf]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports sh_phi1d_sup]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports sh_phi1d_sup]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports slow_ctrl_ck]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports slow_ctrl_ck]
set_output_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports slow_ctrl_reset_n]
set_output_delay -clock [get_clocks daq_ck] -max -add_delay 1.000 [get_ports slow_ctrl_reset_n]

set_property OFFCHIP_TERM FP_VTT_50 [get_ports inj_stb]
set_input_delay -clock [get_clocks daq_ck] -min -add_delay 0.000 [get_ports btn_reset]
set_input_delay -clock [get_clocks daq_ck] -max -add_delay 10.000 [get_ports btn_reset]
set_input_delay -clock [get_clocks VIRTUAL_uart_ck_reg_n_0] -min -add_delay 0.000 [get_ports rx_ser]
set_input_delay -clock [get_clocks VIRTUAL_uart_ck_reg_n_0] -max -add_delay 5.000 [get_ports rx_ser]
